name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: pmwdigital/.github/.github/workflows/node-ci.yml@main
    with:
      node-version: "22"
      install-command: "npm ci"
      lint-command: "npm run lint"
      typecheck-command: "npm run typecheck"
      test-command: ""
      build-command: "npm run build"
      audit-level: "critical"
